sudo: false
language: python
notifications:
  email: false
env:
  global:
python:
  - 2.7
  - 2.6
  - pypy
  - pypy3
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
script:
  make test
after_success:
  codecov