sudo: false
language: python
notifications:
  email: false
env:
  global:
python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6
  - pypy3
  - pypy
install:
  - rm applymoban.py
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
script:
  make test
after_success:
  codecov
